#!/bin/bash
IPV4_ADDR=192.168.100.100
IPV6_ADDR=fc23::4

. tools.sh

test_count=0
success_count=0

# args: $1 ip
function build_and_check()
{
    # Build linux target with smews_check application
    build_smews $1 linux

    launch_smews $1 linux
    
    for test in `run-parts --list $TESTS_FOLDER/tests` 
    do
	test_count=`expr $test_count + 1`
	if ! $test $1 linux
	then
	    fail $1 linux "TEST:`basename $test`"
	else
	    if pgrep smews.elf > /dev/null
	    then
		success_count=`expr $success_count + 1`
	    else
		fail $1 linux "TEST:`basename $test`:*crash*"
	    fi
	fi
    done

    kill_smews
}

TESTS_FOLDER=`cd \`dirname $0\` && pwd`
if [ $# -eq 1 ]
then
    cd $*
fi

build_and_check $IPV4_ADDR
build_and_check $IPV6_ADDR

echo "$success_count/$test_count tests passed"
