#!/bin/bash

. tools.sh

test_count=0
success_count=0

# args: $1 ip
# args: $2 target
function build_and_check()
{
    echo "Checking ip $1 for target $2"
    # Build linux target with smews_check application
    if is_v6 $1
    then
	more_app=icmpv6
    else
	more_app=""
    fi
    if ! build_smews $1 $2 $more_app
    then
	return 1
    fi

    
    for test in `run-parts --list $TESTS_FOLDER/tests` 
    do
	if ! is_alive $1 $2
	then
	    if ! launch_smews $1 $2
	    then
		return 1
	    fi
	fi

	test_count=`expr $test_count + 1`
	if ! $test $1 $2
	then
	    fail $1 $2 "TEST:`basename $test`"
	else
	    if is_alive $1 $2
	    then
		echo -n "."
		success_count=`expr $success_count + 1`
	    else
		fail $1 $2 "TEST:`basename $test`:*crash*"
	    fi
	fi
    done
    kill_smews $1 $2
    echo ""
}

TESTS_FOLDER=`cd \`dirname $0\` && pwd`
if [ $# -eq 1 ]
then
    cd $*
fi

build_and_check 192.168.100.4 linux
build_and_check fc23::4 linux

build_and_check 192.168.100.2 mbed_ethernet
build_and_check fc23::2 mbed_ethernet


if [ "$test_count" -eq 0 ]
then
    echo "No test performed!"
    exit 1
fi

echo "$success_count/$test_count tests passed"

test $success_count -eq $test_count
