#!/bin/bash

. tools.sh

test_count=0
success_count=0

# args: $1 ip
# args: $2 target
function build_and_check()
{
    echo "Checking ip $1 for target $2"
    # Build linux target with smews_check application
    if ! build_smews $1 $2
    then
	return 1
    fi

    
    for test in `run-parts --list $TESTS_FOLDER/tests` 
    do
	if ! launch_smews $1 $2
	then
	    return 1
	fi

	test_count=`expr $test_count + 1`
	if ! $test $1 $2
	then
	    fail $1 linux "TEST:`basename $test`"
	else
	    if pgrep smews.elf > /dev/null
	    then
		echo -n "."
		success_count=`expr $success_count + 1`
	    else
		fail $1 $2 "TEST:`basename $test`:*crash*"
	    fi
	fi
	kill_smews
    done
    echo ""
}

TESTS_FOLDER=`cd \`dirname $0\` && pwd`
if [ $# -eq 1 ]
then
    cd $*
fi

build_and_check 192.168.100.4 linux
build_and_check fc23::4 linux

build_and_check 192.168.100.2 mbed_ethernet
build_and_check fc23::2 mbed_ethernet


if [ "$test_count" -eq 0 ]
then
    echo "No test performed!"
    exit 1
fi

echo "$success_count/$test_count tests passed"

test $success_count -eq $test_count
