#!/usr/bin/env python3

import sys, os
from modules import *

def what(action, test_suite, build_options):
    return "{};{};{}".format(action, test_suite, smews.build_options_to_string(build_options))


def test_build(test_suite, build_options):
    test.begin(build_options["target"], what("build", test_suite, build_options))
    try:
        smews.build(build_options)
        test.success()
        return True
    except smews.SmewsError as e:
        test.fail(e.message)
    return False



def test_program(test_suite, build_options):
    test.begin(build_options["target"], what("program", test_suite, build_options))
    try:
        smews.program(build_options["target"])
        test.success()
        return True
    except smews.SmewsError as e:
        test.fail(e.message)
    return False

def test_run(test_suite, build_options):
    test.begin(build_options["target"], what("run", test_suite, build_options))
    try:
        smews.run(build_options["target"])
        test.success()
        return True
    except smews.SmewsError as e:
        test.fail(e.message)
    return False

def do_test(test_script, test_suite, build_options):
    test.begin(build_options["target"], what(os.path.basename(test_script), test_suite, build_options))
    try:
        args = [test_script, build_options["ipaddr"]]
        system.execute(args)
        test.success()
        return True
    except system.ExecutionError as e:
        test.fail(e.message)
    return False

def do_tests(test_suite, build_options):
    # Get script to execute
    tests = test_suites.get_tests(test_suite, build_options["target"])    
    for test in tests:
        do_test(test, test_suite, build_options)

def test_kill(test_suite, build_options):
    test.begin(build_options["target"], what("kill", test_suite, build_options))
    try:
        smews.kill(build_options["target"])
        test.success()
        return True
    except smews.SmewsError as e:
        test.fail(e.message)
    return False


def ip_from_target(ip,target):
    available_targets = smews.get_target_list()
    return ip.format(available_targets.index(target)+10)

def is_v6(ip):
    return ':' in ip

if len(sys.argv) < 2:
    sys.stderr.write("Usage: {0} <smews_folder> [logfile=<file>] [targets=<target1,...,targetN] [test_suites=ts1,...,tsN] [tests=test1,...,testN] [disable=<configuration>] [ips=ip1,...,ipN]\n".format(sys.argv[0]))
    sys.stderr.write("\nOptions list:\n")
    sys.stderr.write("- logfile: the name of the log file to generate (defaults to 'test.csv')\n")
    sys.stderr.write("- targets: a comma separated list of targets to test (defaults to all smews available targets)\n")
    sys.stderr.write("- test_suites: a comma separated list of test_suites to run (defaults to all suites available in 'tests' folder)\n")
    sys.stderr.write("- tests: a comma separated list of tests script to run (defaults to all tests in the suites)\n")
    sys.stderr.write("- disable: a comma separated list of disable smews options. This will be used as the *only* tested configuration. (defaults to testing all possible combination of disable options in smews)\n")
    sys.stderr.write("- ips: a comma separated list ips addresses to build smews with. If {} is used in the string, it will be replaced by a different number for each target. (defaults to '192.168.100.{}' and 'fc23::{}')\n")
    sys.exit(1)

# Set needed folder to absolute paths
script_folder = os.path.abspath(sys.path[0])
test.log_file = os.path.join(script_folder, "test.csv")
smews.folder = os.path.abspath(sys.argv[1])
smews.tools_folder = os.path.join(script_folder, "tools")
# update the PATH environment so that all run scripts have a direct access to the tools scripts
os.environ["PATH"] = os.environ["PATH"] + ":" + smews.tools_folder
test_suites.folder = os.path.join(script_folder, "test_suites")


targets_to_test = []
test_suites_to_test = []
disable = []

ips = ["192.168.100.{}", "fc23::{}"]

for arg in sys.argv[2:]:
    if arg.startswith("targets="):
        t, e, targets = arg.partition("=")
        targets_to_test = targets.split(",")
    if arg.startswith("test_suites="):
        t, e, ts = arg.partition("=")
        test_suites_to_test = ts.split(",")
    if arg.startswith("logfile="):
        l, e, log = arg.partition("=")
        test.log_file = os.path.abspath(log)
    if arg.startswith("tests="):
        t, e, tests = arg.partition("=")
        test_suites.only = tests.split(",")
    if arg.startswith("disable="):
        t, e, dis = arg.partition("=")
        disable = dis.split(",")
    if arg.startswith("ips="):
        t, e, iplist = arg.partition("=")
        ips = iplist.split(",")




try:
    test_suites_list = test_suites.get_list()

    if len(test_suites_to_test):
        test_suites_list = list(set(test_suites_list) & set(test_suites_to_test))

    last_suite = None
    for test_suite in test_suites_list:
        last_suite = test_suite
        targets = test_suites.get_targets_to_test(test_suite)
        if len(targets_to_test):
            targets = list(set(targets) & set(targets_to_test))
        apps = test_suites.get_apps_to_include(test_suite)
        # Copy needed apps to smews folder
        test_suites.copy_apps(test_suite)
        disable_list = test_suites.get_disable_list(test_suite)
        if len(disable):
            disable_list = [disable]
        build_options = {}
        for target in targets:
            build_options["target"] = target
            for ip in ips:
                ip = ip_from_target(ip, target)
                build_options["ipaddr"] = ip                
                for disable in disable_list:
                    build_options["disable"] = ",".join(disable)
                    build_options["apps"] = ",".join(apps)
                    if is_v6(ip):
                        build_options["apps"] = build_options["apps"] + "," + "icmpv6"
                    # Build smews
                    if test_build(test_suite, build_options):
                        # Flash to device
                        if test_program(test_suite, build_options):
                            # Run smews
                            if test_run(test_suite, build_options):
                                # Executes tests
                                do_tests(test_suite, build_options)
                                # Kill
                                test_kill(test_suite, build_options)
        # Clean smews folder
        test_suites.remove_apps(test_suite)
        last_suite = None

except KeyboardInterrupt:
    sys.stderr.write("\nAbording tests\n")
finally:
    if (last_suite):
        test_suites.remove_apps(last_suite)
    test.report(False)
