#!/bin/bash

SCRIPT_FOLDER=`cd \`dirname $0\` && pwd`
LOG_FOLDER=$SCRIPT_FOLDER/logs
SMEWS_FOLDER=$1
SMEWS_URL=git://github.com/2xs/smews.git

# Ensure smews is present
test -d $SMEWS_FOLDER || git clone $SMEWS_URL $SMEWS_FOLDER || exit 1
test -f $SMEWS_FOLDER/SConstruct || exit 2

mkdir -p $LOG_FOLDER

SMEWS_FOLDER=`cd $SMEWS_FOLDER && pwd` # get absolute path

cd $SMEWS_FOLDER
BRANCHES=`cd $SMEWS_FOLDER && git branch -a | grep origin | grep -v HEAD | sed 's/\*//g'`
echo $BRANCHES
for b in $BRANCHES
do
    local_branch=`echo $b | cut -d/ -f3-`
    # switch to branch
    git checkout -t $b
    # update branch
    git pull
    # Check if test has already been run
    HASH=`git log --oneline --no-abbrev | cut -d\  -f1 | head -1`
    if ! test -f $LOG_FOLDER/*-$HASH.csv
    then
	# Run tests
	$SCRIPT_FOLDER/smews_test $SMEWS_FOLDER logfile=$LOG_FOLDER/$local_branch-`date +%Y%m%d%H%M%s`-$HASH.csv
    fi
done


# Local Variables:
# mode: sh
# End:
