#!/usr/bin/env python

import sys,termios

if len(sys.argv) == 2:
    tty = sys.argv[1]
else:
    sys.stderr.write("Usage: {} <tty_file>\n".format(sys.argv[0]))
    sys.exit(1)


try:
    fd = open(tty)
    termios.tcsendbreak(fd,0)
except IOError as e:
    sys.stderr.write("Cannot open " + tty + ": " + e.strerror + "\n")
except:
    sys.stderr.write("Unexpected error: " + sys.exc_info()[0] + "\n")
    raise
